from setuptools import setup, find_packages

setup(
    name="pubmed-mcp-server",
    version="1.0.0",
    description="A comprehensive PubMed Model Context Protocol (MCP) server",
    long_description="A full-featured MCP server for searching and accessing PubMed literature with advanced search capabilities, citation management, and export features.",
    author="Agent Care Team",
    packages=find_packages(),
    install_requires=[
        "fastapi>=0.115.0",
        "uvicorn[standard]>=0.32.0",
        "httpx>=0.28.0",
        "pydantic>=2.10.0",
        "python-dotenv>=1.0.0",
        "cachetools>=5.5.0",
        "mcp>=1.1.0",
        "python-multipart>=0.0.18",
        "aiofiles>=24.1.0",
        "lxml>=5.1.0",
        "beautifulsoup4>=4.12.0",
        "python-dateutil>=2.8.0",
        "bibtexparser>=1.4.0",
        "jinja2>=3.1.0",
    ],
    python_requires=">=3.8",
    entry_points={
        "console_scripts": [
            "pubmed-mcp=src.main:main",
        ],
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Healthcare Industry",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Scientific/Engineering :: Medical Science Apps.",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
) 